name: Import Issues to Jira

on:
  issues:
    types: [opened]

jobs:
  import_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download issues from GitHub
      run: |
        curl -i https://api.github.com/repos/Rikicavaz77/MTSS-Assignment-2/issues > issues.json || echo "Failed to download issues.json"

    - name: Upload issues.json as artifact
      uses: actions/upload-artifact@v2
      with:
        name: issues
        path: issues.json
          
    - name: Visualizza il contenuto di issues.json
      run: cat issues.json

    - name: Convert JSON to CSV
      run: |
        python convert_to_csv.py issues.json issues.csv

    - name: Import issues to Jira
      run: |
        curl -X POST \
          -H "Authorization: Bearer $ATATT3xFfGF0WiBpzCtLPxI2-rCyF8y2HMcyQDGoSfjs7ZtlvTZ6Hj5Wc0fis4_kcvrKHVT9gLXsqbd9LUH2acNwTwcAV0sfMdOoEBT9HjDRuE40PB3IgWklZxiXu5hXyDTZd3UK17jfvKxo37ytnj4844z5JXvBw4IF4D-sBOLp55fi0g87YsE=58C1327E" \
          -H "Content-Type: application/json" \
          -d @issues.csv \
          https://argo-swe.atlassian.net//rest/api/latest/import/csv
